'use client'

import "./globals.css";
import { Public_Sans } from "next/font/google";
import { Provider } from "react-redux";
import store from '@/app/store'
const publicSans = Public_Sans({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body 
          className={publicSans.className}
          style={{
            backgroundColor: '#F4F7FA'
          }}
          >
            <Provider store={store}>
              {children}
            </Provider>
        </body>
      </html>
    </>
  );
}
