'use client'

import { PrimeReactProvider } from 'primereact/api'

import './globals.css';
import 'primeicons/primeicons.css'
import 'primeflex/primeflex.css'
import 'primereact/resources/themes/lara-light-indigo/theme.css'
import { Public_Sans } from 'next/font/google';
import { AuthProvider } from '@/app/libs/providers/AuthContext';

const publicSans = Public_Sans({ subsets: ['latin'] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <body 
          className={publicSans.className}
          style={{
            backgroundColor: '#F4F7FA'
          }}
        >
          <AuthProvider>
            <PrimeReactProvider>
              {children}
            </PrimeReactProvider>
          </AuthProvider>
        </body>
      </html>
    </>
  );
}
